# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}
  #COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}
  SHA_ID: ${{ github.sha }}
  
jobs:

  firstechojob:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script and other things
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "Commit ID : " ${SHA_ID::7}
#Create auth.json
      #- name: Create auth.json
        #run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json    
## Build the image
      - name: build
        #env:
          #COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}
          #COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}
        run: docker build -t nginx-latest --build-arg AUTH=$COMPOSER_AUTH .
