# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  SHA_ID: ${{ github.sha }}
  COMPOSER_AUTH_JSON: ${{ .secrets.COMPOSER_AUTH_JSON }}
  
jobs:

  firstechojob:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script and other things
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "Commit ID : " ${SHA_ID::7}
          
      - name: ssh thing
        run: |
          mkdir .ssh
          ssh-keyscan -H github.com >> .ssh/known_hosts
      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.2
          php_extensions: mcrypt pcntl pdo pdo_mysql
          version: 2
          command: install
          quiet: no
          progress: yes
          COMPOSER_AUTH_JSON: ${{ .secrets.COMPOSER_AUTH_JSON }}
